[project]
name = "trdl-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tomvand", email = "tomvand@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.135.1",
    "uvicorn[standard]>=0.41.0",
]

[project.scripts]
trdl-web = "trdl_web.__main__:main"

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.15.5",
]
